services:
  splunk:
    image: splunk/splunk:9.4
    platform: linux/amd64
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - 8000:8000
      - 8089:8089
